# Generated by Django 3.1.4 on 2025-03-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(max_length=255)),
                ('number_of_places_available', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
